### ISSUE TITLE
Registration form not working

### ISSUE THREAD

**Issue by toaster8** [rollerworks/RollerworksMultiUserBundle#21]
Hi,

I have configured this bundle, with latest 2.3.6 but when I try to use the register action I get the following error when submitting form.

```
You have requested a non-existent service "fos_user.listener.email_confirmation".
```

Is there anything special to do to get registration working ?

Also setting: 

```
registration:
        confirmation:
            enabled: false
            template:
                confirmed: AcmeUserBundle:Registration:confirmed.html.twig
```

Doesn't disable the email confirmation.

And last but not least, when this bundle is enabled, the Not Called Listeners section in debug is not shown at all.

Don't know where i did something wrong, everything seems to be configured like in the doc.

Anyway, I really need to know if I can work with this bundle (which I like) or if I need to find another solution.
