### ISSUE TITLE
ParameterNotFoundException:  "admin_user.mailer.default" 

### ISSUE THREAD

**Issue by d00001** [rollerworks/RollerworksMultiUserBundle#33]
``` php
ParameterNotFoundException: The service "admin_user.mailer.default" has a dependency on a non-existent parameter "admin_user.registration.confirmation.email.template". Did you mean one of these: "fos_user.registration.confirmation.template", "fos_user.registration.confirmation.from_email", "fos_user.registration.confirmation.enabled"?
```

Any Ideas why I am getting this?

Extension:

``` php
  public function load(array $configs, ContainerBuilder $container)
    {
        $configuration = new Configuration();
        $config = $this->processConfiguration($configuration, $configs);

        $factory = new UserServicesFactory($container);
        $factory->create('admin_user', $config);


        $loader = new Loader\YamlFileLoader($container, new FileLocator(__DIR__ . '/../Resources/config'));
        $loader->load('services.yml');
    }
```

Configuration:

``` php
 public function getConfigTreeBuilder()
    {
        $treeBuilder = new TreeBuilder();
        $rootNode = $treeBuilder->root('acme_admin');

        // Here you should define the parameters that are allowed to
        // configure your bundle. See the documentation linked above for
        // more information on that topic.

        $userConfig = new \Rollerworks\Bundle\MultiUserBundle\DependencyInjection\Configuration();

        $userTreeBuilder = new TreeBuilder();
        $userNode = $userTreeBuilder->root('user');

        $rootNode->append($userConfig->addUserConfig($userNode));

        return $treeBuilder;
    }
```

config.yml

```
acme_admin:
  user:
    user_class: Acme\AdminBundle\Entity\AdminUser
    path: ^/admin
    services_prefix: admin_user
    routes_prefix: admin_user
    db_driver:  orm
    firewall_name: admin
    model_manager_name: site
```

composer.json

```
 "rollerworks/multi-user-bundle": "1.0.*@dev",
  "friendsofsymfony/user-bundle": "~2.0@dev"
```
