### ISSUE TITLE
You must configure the check path to be handled by the firewall using form_login in your security firewall configuration

### ISSUE THREAD

**Issue by truckee** [rollerworks/RollerworksMultiUserBundle#48]
I've wrung out as many (mostly self-inflicted) error messages as I can and am left with

> You must configure the check path to be handled by the firewall using form_login in your security firewall configuration

I get a login template at /staff/profile/login.  The above error appears after submitting the form.

app/config/routing.yml snippet:

```
vol_staff_security:
    resource: "@VolStaffBundle/Resources/config/routing/security.xml"
    prefix: /staff/profile

vol_staff_profile:
    resource: "@VolStaffBundle/Resources/config/routing/profile.xml"
    prefix: /staff/profile

vol_staff_register:
    resource: "@VolStaffBundle/Resources/config/routing/registration.xml"
    prefix: /staff/register

vol_staff_resetting:
    resource: "@VolStaffBundle/Resources/config/routing/resetting.xml"
    prefix: /staff/resetting

vol_staff_change_password:
    resource: "@VolStaffBundle/Resources/config/routing/change_password.xml"
    prefix: /staff/profile
```

app/config/security.yml firewall snippet

```
        staff:
            pattern: ^/staff
            form_login:
                provider: vol_staff_bundle
                csrf_provider: form.csrf_provider
                check_path: vol_staff_security_check
                login_path: vol_staff_security_login
            logout:       true
            anonymous:    true
```

[Curiously, omitting the check_path & login_path parameters threw an error.]

Staff Bundle Resources/config/routing/security.xml:

```
<routes xmlns="http://symfony.com/schema/routing"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://symfony.com/schema/routing http://symfony.com/schema/routing/routing-1.0.xsd">

    <route id="vol_staff_security_login" pattern="/login">
        <default key="_controller">FOSUserBundle:Security:login</default>
    </route>

    <route id="vol_staff_security_check" pattern="/login_check">
        <default key="_controller">FOSUserBundle:Security:check</default>
        <requirement key="_method">POST</requirement>
    </route>

    <route id="vol_staff_security_logout" pattern="/logout">
        <default key="_controller">FOSUserBundle:Security:logout</default>
    </route>

</routes>
```
