### ISSUE TITLE
Additional arguments for forms type

### ISSUE THREAD

**Issue by slowprog** [rollerworks/RollerworksMultiUserBundle#66]
Hello,
I'm trying override registration form. And I need some services (@translator or all them from @service_container), but i can't send it. 

With FOSUserBundle I created form.type with additional arguments:

```
acme.registration.form.type:
    class: Acme\OtherBundle\Form\Entity\CustomerRegistrationType
    arguments: [%fos_user.model.user.class%, "@translator"]
    tags:
        - { name: form.type, alias: acme_registration }
```

But with RollerworksMultiUserBundle I have fatal error:

```
Catchable Fatal Error: Argument 2 passed to CustomerRegistrationType::__construct() must be an instance of Symfony\Component\Translation\Translator, none given...
```

Can you help me, please?
