### ISSUE TITLE
Provider Chain

### ISSUE THREAD

**Issue by gfreeau** [rollerworks/RollerworksMultiUserBundle#74]
Is there a way to use the chain provider for login purposes? We have two user systems and we'd like to allow any type of user to login from 1 security route. i.e

``` yml
my_chain_provider:
  chain:
    providers: [acme.admin_provider.username, acme.user_provider.username]
```

After digging into the code, I've learned that the user systems are activated by the discriminator which is modified by various listeners such as on authentication and by request matching. This would be useful in most cases, however by default, it seems we would need a separate login url and firewall for each user type.

Can this be disabled for a simple login that loops through all user systems to see if the request user exists anywhere? What about ensuring that a username is unique across all user systems?

In our application, we don't actually need two user systems, we need 1 user system with multiple user types, i.e each user type has it's own php class and custom fields.
