### ISSUE TITLE
The service "security.authentication.manager" has a dependency on a non-existent service "security.user.provider.concrete.into_people_admin".

### ISSUE THREAD

**Issue by m-stala** [rollerworks/RollerworksMultiUserBundle#94]
Hi,

I'm trying to use RollerworksMultiUserBundle on my symfony application. However I already had an existing bundle with entities and a fosuser class. So I had to create one new bundle, and apply to one existing bundle. I'm pretty new with symfony and fosuserbundle etc and I'm having a hard time implementing everything. At the moment I have following error:

![picture1](https://cloud.githubusercontent.com/assets/10259830/9343899/29bc815c-4605-11e5-9584-5ce64278a208.PNG)

Here is my security.yml

![picture2](https://cloud.githubusercontent.com/assets/10259830/9343919/46da3964-4605-11e5-802d-cd7f2de8e44d.PNG)

**Comment by sstok** [comment]
It seems you haven't configured the mapping of your IntoPeopleAdminBundle.
http://symfony.com/doc/current/cookbook/doctrine/multiple_entity_managers.html

```yaml
doctrine:
   ...

    orm:
        default_entity_manager: default
        entity_managers:
            default:
                connection: default
                mappings:
                    FOSUserBundle:  ...
                    IntoPeopleAdminBundle: ~ # should be automatically configured with this
```

As this is a problem with your Doctrine ORM configuration and not directly related to the RollerworksMultiUserBundle you can get support for Symfony and Doctrine at https://stackoverflow.com/ or the #Symfony IRC channel https://symfony.com/irc
